name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@<SHA>
      - name: Set up JDK 21
        uses: actions/setup-java@<SHA>
        with:
          distribution: temurin
          java-version: 21
          cache: maven
      - name: Build & test (unit)
        run: ./mvnw -B -U -DskipTests=false test

  integration-tests:
    needs: unit-tests
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event.pull_request.head.repo.fork == false }}
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      JAVA_VERSION: "21"
      DOCKER_HOST: "unix:///var/run/docker.sock"
    steps:
      - name: Checkout
        uses: actions/checkout@<SHA>
      - name: Set up JDK 21
        uses: actions/setup-java@<SHA>
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven
      - name: Validate OPENAI_API_KEY presence
        run: |
          if [ -z "${OPENAI_API_KEY}" ]; then
            echo "Missing OPENAI_API_KEY secret"; exit 1; fi
      - name: Verify integration tests (Liquibase + Testcontainers)
        run: ./mvnw -B -P integrationTest verify
